/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package database_project;

/**
 *
 * @author Nethmi
 */
public class Admin extends javax.swing.JFrame {

    /** Creates new form Admin */
    public Admin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin1 = new javax.swing.JLabel();
        admin2 = new javax.swing.JLabel();
        admin3 = new javax.swing.JLabel();
        admin4 = new javax.swing.JLabel();
        admin5 = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin1.setBackground(new java.awt.Color(255, 255, 255));
        admin1.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        admin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin1.setText("Add new patient record");
        admin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        admin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin1.setOpaque(true);
        admin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin1MouseClicked(evt);
            }
        });
        getContentPane().add(admin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 240, 50));

        admin2.setBackground(new java.awt.Color(255, 255, 255));
        admin2.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        admin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin2.setText("Update Health Record");
        admin2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        admin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin2.setOpaque(true);
        admin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin2MouseClicked(evt);
            }
        });
        getContentPane().add(admin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, 45));

        admin3.setBackground(new java.awt.Color(255, 255, 255));
        admin3.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        admin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin3.setText("Add Laboratory Resuls");
        admin3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        admin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin3.setOpaque(true);
        admin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin3MouseClicked(evt);
            }
        });
        getContentPane().add(admin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 240, 45));

        admin4.setBackground(new java.awt.Color(255, 255, 255));
        admin4.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        admin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin4.setText("Update Hospital Information");
        admin4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        admin4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin4.setOpaque(true);
        admin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin4MouseClicked(evt);
            }
        });
        getContentPane().add(admin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 45));

        admin5.setBackground(new java.awt.Color(255, 255, 255));
        admin5.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        admin5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin5.setText("Payment for Doctors");
        admin5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        admin5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin5.setOpaque(true);
        admin5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin5MouseClicked(evt);
            }
        });
        getContentPane().add(admin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 240, 45));

        buttonBack.setBackground(new java.awt.Color(255, 255, 255));
        buttonBack.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        buttonBack.setText("Back to Home Page");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        buttonBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonBackKeyPressed(evt);
            }
        });
        getContentPane().add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 240, 50));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nethmi\\Desktop\\ps\\ADMIN1.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, -6, 760, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin1MouseClicked
        Add_Record newRecord = new Add_Record();
        newRecord.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin1MouseClicked

    private void admin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin2MouseClicked
        UpdateInfo newObj1 = new UpdateInfo();
        newObj1.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin2MouseClicked

    private void admin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin3MouseClicked
        LabResult newObj2 = new LabResult();
        newObj2.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin3MouseClicked

    private void admin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin4MouseClicked
        dispose();
        HospitalInfo hospInfo = new HospitalInfo();
        hospInfo.setVisible(true);
    }//GEN-LAST:event_admin4MouseClicked

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        dispose();
        HomePage homePage = new HomePage(); 
        homePage.setVisible(true);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonBackKeyPressed

    }//GEN-LAST:event_buttonBackKeyPressed

    private void admin5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin5MouseClicked
        Doctor_Payment dPayment = new Doctor_Payment();
        dPayment.setVisible(true);
        dispose();
    }//GEN-LAST:event_admin5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin1;
    private javax.swing.JLabel admin2;
    private javax.swing.JLabel admin3;
    private javax.swing.JLabel admin4;
    private javax.swing.JLabel admin5;
    private javax.swing.JButton buttonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
