/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nethmi
 */
public class Doctor_Payment extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Doctor_Payment() {
        initComponents();
    }

    Connection con;
    PreparedStatement pst;
    int total = 0;
    String date = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCheck = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        name1 = new javax.swing.JLabel();
        calc1 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        dname = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        buttonCheck1 = new javax.swing.JButton();
        buttonCheck2 = new javax.swing.JButton();
        buttonCheck3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctors' Daily payments ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonCheck.setBackground(new java.awt.Color(0, 153, 153));
        buttonCheck.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        buttonCheck.setText("Eye");
        buttonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 40));

        buttonBack.setBackground(new java.awt.Color(0, 153, 153));
        buttonBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 210, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        name1.setBackground(new java.awt.Color(153, 255, 255));
        name1.setFont(new java.awt.Font("Cambria", 2, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));

        calc1.setBackground(new java.awt.Color(255, 255, 204));
        calc1.setFont(new java.awt.Font("Cambria", 2, 24)); // NOI18N
        calc1.setForeground(new java.awt.Color(255, 255, 255));

        total1.setBackground(new java.awt.Color(255, 153, 153));
        total1.setFont(new java.awt.Font("Cambria", 2, 24)); // NOI18N
        total1.setForeground(new java.awt.Color(255, 255, 255));

        dname.setBackground(new java.awt.Color(153, 255, 255));
        dname.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        dname.setForeground(new java.awt.Color(255, 255, 255));
        dname.setText("Doctor's Name");

        name7.setBackground(new java.awt.Color(153, 255, 255));
        name7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        name7.setForeground(new java.awt.Color(255, 255, 255));
        name7.setText("Total payment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calc1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dname, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(name7)
                        .addGap(77, 77, 77))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calc1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 730, 300));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 250, 460));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel3.setText("DOCTORS DAILY PAYMENTS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 450, 40));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 40));

        buttonCheck1.setBackground(new java.awt.Color(0, 153, 153));
        buttonCheck1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        buttonCheck1.setText("Orthopedic");
        buttonCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheck1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, 40));

        buttonCheck2.setBackground(new java.awt.Color(0, 153, 153));
        buttonCheck2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        buttonCheck2.setText("Cardiology");
        buttonCheck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheck2ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCheck2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 40));

        buttonCheck3.setBackground(new java.awt.Color(0, 153, 153));
        buttonCheck3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        buttonCheck3.setText("ENT");
        buttonCheck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheck3ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCheck3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nethmi\\Desktop\\ps\\doSal1.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 800, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckActionPerformed
        try{
            int count = 0;
            Date date = jDateChooser1.getDate();
            SimpleDateFormat date1 = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = date1.format(date);
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/hospital management system","root","");         
            pst = con.prepareStatement("select * from doctor where Doctor_ID = 1");
               ResultSet rsl = pst.executeQuery();    
          if(!rsl.next()){
              JOptionPane.showMessageDialog(this, "ERROR...!");
            }
            else{
              
              String name = rsl.getString("Doctor_Name");
              int charge = rsl.getInt("Charge");
              
              pst = con.prepareStatement("select * from eye_clinic where Date=?");    
              pst.setString(1, strDate);
              rsl = pst.executeQuery();    
              while(rsl.next()){
                count++;
            }             
             total = charge*count;             
             name1.setText("Dr."+name);
             calc1.setText(charge +" * "+ count);
             total1.setText(Integer.toString(total));
            }
        }
           catch(ClassNotFoundException ex){
            Logger.getLogger(Add_Record.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex){
            Logger.getLogger(Add_Record.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCheckActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        Admin admin = new Admin();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheck1ActionPerformed
         try{
            int count = 0;
            Date date = jDateChooser1.getDate();
            SimpleDateFormat date1 = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = date1.format(date);
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/hospital management system","root","");         
            pst = con.prepareStatement("select * from doctor where Doctor_ID = 4");
               ResultSet rsl = pst.executeQuery();    
          if(!rsl.next()){
              JOptionPane.showMessageDialog(this, "ERROR...!");
            }
            else{
              String name = rsl.getString("Doctor_Name");
              int charge = rsl.getInt("Charge");
              
              pst = con.prepareStatement("select * from orthopedic_clinic where Date=?");    
              pst.setString(1, strDate);
              rsl = pst.executeQuery();    
              while(rsl.next()){
                count++;
            }
              
             total = charge*count;             
             name1.setText("Dr."+name);
             calc1.setText(charge +" * "+ count);
             total1.setText(Integer.toString(total));
            }
        }
           catch(ClassNotFoundException ex){
            Logger.getLogger(Add_Record.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex){
            Logger.getLogger(Add_Record.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCheck1ActionPerformed

    private void buttonCheck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheck2ActionPerformed
         try{
            int count = 0;
            Date date = jDateChooser1.getDate();
            SimpleDateFormat date1 = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = date1.format(date);
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/hospital management system","root","");         
            pst = con.prepareStatement("select * from doctor where Doctor_ID = 2");
               ResultSet rsl = pst.executeQuery();    
          if(!rsl.next()){
              JOptionPane.showMessageDialog(this, "ERROR...!");
            }
            else{
              String name = rsl.getString("Doctor_Name");
              int charge = rsl.getInt("Charge");
              
              pst = con.prepareStatement("select * from cardiology_clinic where Date=?");    
              pst.setString(1, strDate);
              rsl = pst.executeQuery();    
              while(rsl.next()){
                count++;
            }
              
             total = charge*count;             
             name1.setText("Dr."+name);
             calc1.setText(charge +" * "+ count);
             total1.setText(Integer.toString(total));
            }
        }
           catch(ClassNotFoundException ex){
            Logger.getLogger(Add_Record.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex){
            Logger.getLogger(Add_Record.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCheck2ActionPerformed

    private void buttonCheck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheck3ActionPerformed
         try{
            int count = 0;
            Date date = jDateChooser1.getDate();
            SimpleDateFormat date1 = new SimpleDateFormat("yyyy-MM-dd");
            String strDate = date1.format(date);
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/hospital management system","root","");         
            pst = con.prepareStatement("select * from doctor where Doctor_ID = 3");
               ResultSet rsl = pst.executeQuery();    
          if(!rsl.next()){
              JOptionPane.showMessageDialog(this, "ERROR...!");
            }
            else{
              String name = rsl.getString("Doctor_Name");
              int charge = rsl.getInt("Charge");
              
              pst = con.prepareStatement("select * from ent_clinic where Date=?");    
              pst.setString(1, strDate);
              rsl = pst.executeQuery();    
              while(rsl.next()){
                count++;
            }
             
             total = charge*count;             
             name1.setText("Dr."+name);
             calc1.setText(charge +" * "+ count);
             total1.setText(Integer.toString(total));
            }
        }
           catch(ClassNotFoundException ex){
            Logger.getLogger(Add_Record.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(SQLException ex){
            Logger.getLogger(Add_Record.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCheck3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCheck;
    private javax.swing.JButton buttonCheck1;
    private javax.swing.JButton buttonCheck2;
    private javax.swing.JButton buttonCheck3;
    private javax.swing.JLabel calc1;
    private javax.swing.JLabel dname;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel total1;
    // End of variables declaration//GEN-END:variables
}
