/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_project;

/**
 *
 * @author Nethmi
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        patientButton = new javax.swing.JButton();
        patient1 = new javax.swing.JLabel();
        patient2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(51, 153, 255));
        setLocation(new java.awt.Point(0, 0));
        setName("Home Page"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(153, 153, 153));
        closeButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        closeButton.setText("Close");
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 130, 47));

        adminButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        adminButton.setText("Admin");
        adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        adminButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminButtonKeyPressed(evt);
            }
        });
        getContentPane().add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 140, 45));

        patientButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        patientButton.setText("Patient ");
        patientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        patientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(patientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 140, 45));

        patient1.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        patient1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient1MouseClicked(evt);
            }
        });
        getContentPane().add(patient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 143, 33));

        patient2.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        patient2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patient2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patient2MouseClicked(evt);
            }
        });
        getContentPane().add(patient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 143, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nethmi\\Desktop\\ps\\copy1.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 800, 590));

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, -6, 220, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed

        LogingPage obj = new LogingPage();
        obj.setVisible(true);        
        dispose();
    
    }//GEN-LAST:event_adminButtonActionPerformed

    private void patient1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient1MouseClicked
       Patient_HR healthRecord = new Patient_HR();
        healthRecord.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_patient1MouseClicked

    private void patientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientButtonActionPerformed
        patient1.setText("Health Record");
        patient2.setText("Bill Details");
    }//GEN-LAST:event_patientButtonActionPerformed

    private void patient2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patient2MouseClicked
       bill newBill = new bill();
       newBill.setVisible(true);
       dispose();
    }//GEN-LAST:event_patient2MouseClicked

    private void adminButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel patient1;
    private javax.swing.JLabel patient2;
    private javax.swing.JButton patientButton;
    // End of variables declaration//GEN-END:variables
}
